- id: check-commit-message
  name: Check for ClickUp ticket ID
  description: Check for ClickUp ticket ID in commit message
  entry: check-commit-message
  language: python
  stages: [commit-msg]
- id: format-dotnet
  name: Format dotnet code
  description: Format dotnet
  entry: format-dotnet
  language: python
  stages: [pre-commit]
